$kind: http-example
name: Successfully updated document settings.
request:
  url: "{{baseUrl}}/public/v2/documents/:document_id/settings"
  method: PATCH
  headers:
    - key: Content-Type
      value: application/json
    - key: Accept
      value: application/json
    - key: Authorization
      value: <API Key>
      description: "Added as a part of security scheme: apikey"
  pathVariables:
    - key: document_id
      value: BhVzRcxH9Z2LgfPPGXFUBa
      description: Unique identifier of the document to update settings for.
  body:
    type: json
    content: |-
      {
        "language": "fr-FR",
        "qualified_electronic_signature": true,
        "expires_in": 60
      }
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "language": "fr-FR",
        "qualified_electronic_signature": true,
        "expires_in": 60
      }
    $type: |-
      {
        "description": "Document settings response.",
        "type": "object",
        "properties": {
          "language": {
            "type": "string",
            "enum": [
              "en-US",
              "fr-FR",
              "it-IT",
              "es-ES",
              "nl-NL",
              "de-DE",
              "pt-BR",
              "pt-PT",
              "pl-PL",
              "sv-SE",
              "cs-CZ",
              "da-DK",
              "el-GR",
              "hu-HU",
              "nb-NO",
              "ro-RO",
              "bg-BG"
            ],
            "description": "Document language code (e.g., 'en-US', 'fr-FR')."
          },
          "qualified_electronic_signature": {
            "type": "boolean",
            "description": "Indicates whether the document requires a Qualified Electronic Signature (QES)\nduring the signing process. If `true`, signers must complete the document using\na third-party qualified electronic signature provider according to supported verification rules.\n"
          },
          "expires_in": {
            "type": "integer",
            "description": "Document expiration in days. If not explicitly set, defaults to the system default expiration.\n",
            "format": "int32"
          }
        },
        "required": [
          "language",
          "qualified_electronic_signature",
          "expires_in"
        ]
      }
order: 1000
